//------------------------------------------------------------------------------
// <autogenerated>
//     This code was generated by a CodeSmith Template.
//
//     DO NOT MODIFY contents of this file. Changes to this
//     file will be lost if the code is regenerated.
//     Author:Yubao Li
// </autogenerated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.ComponentModel.DataAnnotations.Schema;
using System.Text;
using OpenAuth.Repository.Core;

namespace OpenAuth.Repository.Domain
{
    /// <summary>
	/// 程式碼產生器的欄位資訊
	/// </summary>
    [Table("BuilderTableColumn")]
    public partial class BuilderTableColumn : Entity
    {
        public BuilderTableColumn()
        {
          this.TableId= string.Empty;
          this.TableName= string.Empty;
          this.ColumnName= string.Empty;
          this.Comment= string.Empty;
          this.ColumnType= string.Empty;
          this.EntityType= string.Empty;
          this.EntityName= string.Empty;
          this.QueryType= string.Empty;
          this.HtmlType= string.Empty;
          this.EditType= string.Empty;
          this.Sort= 0;
          this.CreateTime= DateTime.Now;
          this.CreateUserId= string.Empty;
          this.UpdateTime= DateTime.Now;
          this.UpdateUserId= string.Empty;
          this.UpdateUserName= string.Empty;
          this.CreateUserName= string.Empty;
        }

        
        /// <summary>
        /// 歸屬表編號
        /// </summary>
        [Description("歸屬表編號")]
        [Browsable(false)]
        public string TableId { get; set; }
        /// <summary>
        /// 表名稱
        /// </summary>
        [Description("表名稱")]
        public string TableName { get; set; }
        /// <summary>
        /// 列名稱
        /// </summary>
        [Description("列名稱")]
        public string ColumnName { get; set; }
        /// <summary>
        /// 列描述
        /// </summary>
        [Description("列描述")]
        public string Comment { get; set; }
        /// <summary>
        /// 列型別
        /// </summary>
        [Description("列型別")]
        public string ColumnType { get; set; }
        /// <summary>
        /// 實體型別
        /// </summary>
        [Description("實體型別")]
        public string EntityType { get; set; }
        /// <summary>
        /// 實體名稱
        /// </summary>
        [Description("實體名稱")]
        public string EntityName { get; set; }
        /// <summary>
        /// 是否主鍵
        /// </summary>
        [Description("是否主鍵")]
        public bool IsKey { get; set; }
        /// <summary>
        /// 是否自增
        /// </summary>
        [Description("是否自增")]
        public bool IsIncrement { get; set; }
        /// <summary>
        /// 是否必填
        /// </summary>
        [Description("是否必填")]
        public bool IsRequired { get; set; }
        /// <summary>
        /// 是否為插入欄位
        /// </summary>
        [Description("是否為插入欄位")]
        public bool IsInsert { get; set; }
        /// <summary>
        /// 是否編輯欄位
        /// </summary>
        [Description("是否編輯欄位")]
        public bool IsEdit { get; set; }
        /// <summary>
        /// 是否列表欄位
        /// </summary>
        [Description("是否列表欄位")]
        public bool IsList { get; set; }
        /// <summary>
        /// 是否查詢欄位
        /// </summary>
        [Description("是否查詢欄位")]
        public bool IsQuery { get; set; }
        /// <summary>
        /// 查詢方式（等於、不等於、大於、小於、範圍）
        /// </summary>
        [Description("查詢方式（等於、不等於、大於、小於、範圍）")]
        public string QueryType { get; set; }
        /// <summary>
        /// 顯示型別（文字框、文字域、下拉框、覈取方塊、單選框、日期控制元件）
        /// </summary>
        [Description("顯示型別（文字框、文字域、下拉框、覈取方塊、單選框、日期控制元件）")]
        public string HtmlType { get; set; }
        /// <summary>
        /// 編輯型別（文字框、文字域、下拉框、覈取方塊、單選框、日期控制元件）
        /// </summary>
        [Description("編輯型別（文字框、文字域、下拉框、覈取方塊、單選框、日期控制元件）")]
        public string EditType { get; set; }
        /// <summary>
        /// 排序
        /// </summary>
        [Description("排序")]
        public int Sort { get; set; }
        /// <summary>
        /// 建立時間
        /// </summary>
        [Description("建立時間")]
        public System.DateTime CreateTime { get; set; }
        /// <summary>
        /// 建立人ID
        /// </summary>
        [Description("建立人ID")]
        [Browsable(false)]
        public string CreateUserId { get; set; }
        /// <summary>
        /// 修改時間
        /// </summary>
        [Description("修改時間")]
        public System.DateTime? UpdateTime { get; set; }
        /// <summary>
        /// 修改人ID
        /// </summary>
        [Description("修改人ID")]
        [Browsable(false)]
        public string UpdateUserId { get; set; }
        /// <summary>
        /// 修改時的行位置
        /// </summary>
        [Description("修改時的行位置")]
        public int? EditRow { get; set; }
        /// <summary>
        /// 修改時的列位置
        /// </summary>
        [Description("修改時的列位置")]
        public int? EditCol { get; set; }
        /// <summary>
        /// 修改人姓名
        /// </summary>
        [Description("修改人姓名")]
        public string UpdateUserName { get; set; }
        /// <summary>
        /// 建立人姓名
        /// </summary>
        [Description("建立人姓名")]
        public string CreateUserName { get; set; }
        /// <summary>
        /// 最大長度
        /// </summary>
        [Description("最大長度")]
        public int? MaxLength { get; set; }
        
        /// <summary>
        /// 資料來源（用於下拉框、覈取方塊等取值）
        /// </summary>
        [Description("資料來源（用於下拉框、覈取方塊等取值）")]
        public string DataSource { get; set; }
    }
}