//------------------------------------------------------------------------------
// <autogenerated>
//     This code was generated by a CodeSmith Template.
//
//     DO NOT MODIFY contents of this file. Changes to this
//     file will be lost if the code is regenerated.
//     Author:Yubao Li
// </autogenerated>
//------------------------------------------------------------------------------
using System;
using System.ComponentModel;
using System.ComponentModel.DataAnnotations.Schema;
using OpenAuth.Repository.Core;

namespace OpenAuth.Repository.Domain
{
    /// <summary>
	/// 分類型別
	/// </summary>
      [Table("CategoryType")]
    public partial class CategoryType : Entity
    {
        public CategoryType()
        {
          this.Name= string.Empty;
          this.CreateTime= DateTime.Now;
        }

        /// <summary>
	    /// 名稱
	    /// </summary>
         [Description("名稱")]
        public string Name { get; set; }
        /// <summary>
	    /// 建立時間
	    /// </summary>
         [Description("建立時間")]
        public System.DateTime CreateTime { get; set; }

    }
}