//------------------------------------------------------------------------------
// <autogenerated>
//     This code was generated by a CodeSmith Template.
//
//     DO NOT MODIFY contents of this file. Changes to this
//     file will be lost if the code is regenerated.
//     Author:Yubao Li
// </autogenerated>
//------------------------------------------------------------------------------
using System;
using System.ComponentModel;
using System.ComponentModel.DataAnnotations.Schema;
using OpenAuth.Repository.Core;

namespace OpenAuth.Repository.Domain
{
    /// <summary>
	/// 系統授權規制表
	/// </summary>
    [Table("DataPrivilegeRule")]
    public partial class DataPrivilegeRule : Entity
    {
        public DataPrivilegeRule()
        {
          this.SourceCode= string.Empty;
          this.SubSourceCode= string.Empty;
          this.Description= string.Empty;
          this.SortNo= 0;
          this.PrivilegeRules= string.Empty;
          this.CreateTime= DateTime.Now;
          this.CreateUserId= string.Empty;
          this.CreateUserName= string.Empty;
          this.UpdateTime= DateTime.Now;
          this.UpdateUserId= string.Empty;
          this.UpdateUserName= string.Empty;
        }

        /// <summary>
        /// 資源標識（模組編號）
        /// </summary>
        [Description("模組編號")]
        public string SourceCode { get; set; }
        /// <summary>
        /// 二級資源標識
        /// </summary>
        [Description("二級資源標識")]
        [Browsable(false)]
        public string SubSourceCode { get; set; }
        /// <summary>
        /// 許可權描述
        /// </summary>
        [Description("許可權描述")]
        public string Description { get; set; }
        /// <summary>
        /// 排序號
        /// </summary>
        [Description("排序號")]
        public int SortNo { get; set; }
        /// <summary>
        /// 許可權規則
        /// </summary>
        [Description("許可權規則")]
        public string PrivilegeRules { get; set; }
        /// <summary>
        /// 是否可用
        /// </summary>
        [Description("是否可用")]
        public bool Enable { get; set; }
        /// <summary>
        /// 建立時間
        /// </summary>
        [Description("建立時間")]
        public System.DateTime CreateTime { get; set; }
        /// <summary>
        /// 建立人ID
        /// </summary>
        [Description("建立人ID")]
        [Browsable(false)]
        public string CreateUserId { get; set; }
        /// <summary>
        /// 建立人
        /// </summary>
        [Description("建立人")]
        public string CreateUserName { get; set; }
        /// <summary>
        /// 最後更新時間
        /// </summary>
        [Description("最後更新時間")]
        public System.DateTime? UpdateTime { get; set; }
        /// <summary>
        /// 最後更新人ID
        /// </summary>
        [Description("最後更新人ID")]
        [Browsable(false)]
        public string UpdateUserId { get; set; }
        /// <summary>
        /// 最後更新人
        /// </summary>
        [Description("最後更新人")]
        public string UpdateUserName { get; set; }
    }
}