//------------------------------------------------------------------------------
// <autogenerated>
//     This code was generated by a CodeSmith Template.
//
//     DO NOT MODIFY contents of this file. Changes to this
//     file will be lost if the code is regenerated.
//     Author:Yubao Li
// </autogenerated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.ComponentModel.DataAnnotations.Schema;
using System.Text;
using OpenAuth.Repository.Core;

namespace OpenAuth.Repository.Domain
{
    /// <summary>
	/// 定時任務
	/// </summary>
    [Table("OpenJob")]
    public partial class OpenJob : Entity
    {
        public OpenJob()
        {
          this.JobName= string.Empty;
          this.RunCount= 0;
          this.ErrorCount= 0;
          this.NextRunTime= DateTime.Now;
          this.LastRunTime= DateTime.Now;
          this.LastErrorTime= DateTime.Now;
          this.JobType= 0;
          this.JobCall= string.Empty;
          this.JobCallParams= string.Empty;
          this.Cron= string.Empty;
          this.Status= 0;
          this.Remark= string.Empty;
          this.CreateTime= DateTime.Now;
          this.CreateUserId= string.Empty;
          this.CreateUserName= string.Empty;
          this.UpdateTime= DateTime.Now;
          this.UpdateUserId= string.Empty;
          this.UpdateUserName= string.Empty;
          this.OrgId= string.Empty;
        }

        
        /// <summary>
        /// 任務名稱
        /// </summary>
        [Description("任務名稱")]
        public string JobName { get; set; }
        /// <summary>
        /// 任務執行次數
        /// </summary>
        [Description("任務執行次數")]
        public int RunCount { get; set; }
        /// <summary>
        /// 異常次數
        /// </summary>
        [Description("異常次數")]
        public int ErrorCount { get; set; }
        /// <summary>
        /// 下次執行時間
        /// </summary>
        [Description("下次執行時間")]
        public System.DateTime? NextRunTime { get; set; }
        /// <summary>
        /// 最後一次執行時間
        /// </summary>
        [Description("最後一次執行時間")]
        public System.DateTime? LastRunTime { get; set; }
        /// <summary>
        /// 最後一次失敗時間
        /// </summary>
        [Description("最後一次失敗時間")]
        public System.DateTime? LastErrorTime { get; set; }
        /// <summary>
        /// 任務執行方式0：本地任務；1：外部接口任務
        /// </summary>
        [Description("任務執行方式0：本地任務；1：外部接口任務")]
        public int JobType { get; set; }
        /// <summary>
        /// 任務地址
        /// </summary>
        [Description("任務地址")]
        public string JobCall { get; set; }
        /// <summary>
        /// 任務參數，JSON格式
        /// </summary>
        [Description("任務參數，JSON格式")]
        public string JobCallParams { get; set; }
        /// <summary>
        /// CRON表達式
        /// </summary>
        [Description("CRON表達式")]
        public string Cron { get; set; }
        /// <summary>
        /// 任務執行狀態（0：停止，1：正在執行，2：暫停）
        /// </summary>
        [Description("任務執行狀態（0：停止，1：正在執行，2：暫停）")]
        public int Status { get; set; }
        /// <summary>
        /// 備註
        /// </summary>
        [Description("備註")]
        public string Remark { get; set; }
        /// <summary>
        /// 建立時間
        /// </summary>
        [Description("建立時間")]
        public System.DateTime CreateTime { get; set; }
        /// <summary>
        /// 建立人ID
        /// </summary>
        [Description("建立人ID")]
        [Browsable(false)]
        public string CreateUserId { get; set; }
        /// <summary>
        /// 建立人
        /// </summary>
        [Description("建立人")]
        public string CreateUserName { get; set; }
        /// <summary>
        /// 最後更新時間
        /// </summary>
        [Description("最後更新時間")]
        public System.DateTime? UpdateTime { get; set; }
        /// <summary>
        /// 最後更新人ID
        /// </summary>
        [Description("最後更新人ID")]
        [Browsable(false)]
        public string UpdateUserId { get; set; }
        /// <summary>
        /// 最後更新人
        /// </summary>
        [Description("最後更新人")]
        public string UpdateUserName { get; set; }
        /// <summary>
        /// 所屬部門
        /// </summary>
        [Description("所屬部門")]
        [Browsable(false)]
        public string OrgId { get; set; }
    }
}