//------------------------------------------------------------------------------
// <autogenerated>
//     This code was generated by a CodeSmith Template.
//
//     DO NOT MODIFY contents of this file. Changes to this
//     file will be lost if the code is regenerated.
//     Author:Yubao Li
// </autogenerated>
//------------------------------------------------------------------------------
using System;
using System.ComponentModel;
using System.ComponentModel.DataAnnotations.Schema;
using OpenAuth.Repository.Core;

namespace OpenAuth.Repository.Domain
{
    /// <summary>
	/// 使用者基本資訊表
	/// </summary>
      [Table("User")]
    public partial class User : Entity
    {
        public User()
        {
          this.Account= string.Empty;
          this.Password= string.Empty;
          this.Name= string.Empty;
          this.Sex= 0;
          this.Status= 0;
          this.BizCode= string.Empty;
          this.CreateTime= DateTime.Now;
          this.CreateId= string.Empty;
          this.TypeName= string.Empty;
          this.TypeId= string.Empty;
        }

        /// <summary>
	    /// 使用者登錄帳號
	    /// </summary>
         [Description("使用者登錄帳號")]
        public string Account { get; set; }
        /// <summary>
	    /// 密碼
	    /// </summary>
         [Description("密碼")]
        public string Password { get; set; }
        /// <summary>
	    /// 使用者姓名
	    /// </summary>
         [Description("使用者姓名")]
        public string Name { get; set; }
        /// <summary>
	    /// 性別
	    /// </summary>
         [Description("性別")]
        public int Sex { get; set; }
        /// <summary>
	    /// 使用者狀態
	    /// </summary>
         [Description("使用者狀態")]
        public int Status { get; set; }
        /// <summary>
	    /// 業務對照碼
	    /// </summary>
         [Description("業務對照碼")]
        public string BizCode { get; set; }
        /// <summary>
	    /// 經辦時間
	    /// </summary>
         [Description("經辦時間")]
        public System.DateTime CreateTime { get; set; }
        /// <summary>
	    /// 建立人
	    /// </summary>
         [Description("建立人")]
        public string CreateId { get; set; }
        /// <summary>
	    /// 分類名稱
	    /// </summary>
         [Description("分類名稱")]
        public string TypeName { get; set; }
        /// <summary>
	    /// 分類ID
	    /// </summary>
         [Description("分類ID")]
        public string TypeId { get; set; }

    }
}