//------------------------------------------------------------------------------
// <autogenerated>
//     This code was generated by a CodeSmith Template.
//
//     DO NOT MODIFY contents of this file. Changes to this
//     file will be lost if the code is regenerated.
//     Author:Yubao Li
// </autogenerated>
//------------------------------------------------------------------------------
using System;
using System.ComponentModel;
using System.ComponentModel.DataAnnotations.Schema;
using OpenAuth.Repository.Core;

namespace OpenAuth.Repository.Domain
{
    /// <summary>
	/// 入庫通知單（入庫訂單）
	/// </summary>
    [Table("WmsInboundOrderTbl")]
    public partial class WmsInboundOrderTbl : Entity
    {
        public WmsInboundOrderTbl()
        {
          this.ExternalNo= string.Empty;
          this.ExternalType= string.Empty;
          this.Status= 0;
          this.OrderType= string.Empty;
          this.GoodsType= string.Empty;
          this.PurchaseNo= string.Empty;
          this.StockId= string.Empty;
          this.OwnerId= string.Empty;
          this.ShipperId= string.Empty;
          this.SupplierId= string.Empty;
          this.ScheduledInboundTime= DateTime.Now;
          this.Remark= string.Empty;
          this.TransferType= string.Empty;
          this.ReturnBoxNum= 0;
          this.CreateTime= DateTime.Now;
          this.CreateUserId= string.Empty;
          this.CreateUserName= string.Empty;
          this.UpdateTime= DateTime.Now;
          this.UpdateUserId= string.Empty;
          this.UpdateUserName= string.Empty;
        }

        
        /// <summary>
        /// 相關單據號
        /// </summary>
        [Description("相關單據")]
        public string ExternalNo { get; set; }
        /// <summary>
        /// 相關單據型別
        /// </summary>
        [Description("相關單據型別")]
        [Browsable(false)]
        public string ExternalType { get; set; }
        /// <summary>
        /// 狀態
        /// </summary>
        [Description("狀態")]
        public int Status { get; set; }
        /// <summary>
        /// 入庫型別
        /// </summary>
        [Description("入庫型別")]
        public string OrderType { get; set; }
        /// <summary>
        /// 商品類別
        /// </summary>
        [Description("商品類別")]
        public string GoodsType { get; set; }
        /// <summary>
        /// 採購單號
        /// </summary>
        [Description("採購單號")]
        public string PurchaseNo { get; set; }
        /// <summary>
        /// 倉庫編號
        /// </summary>
        [Description("倉庫編號")]
        [Browsable(false)]
        public string StockId { get; set; }
        /// <summary>
        /// 貨主
        /// </summary>
        [Description("貨主")]
        [Browsable(false)]
        public string OwnerId { get; set; }
        /// <summary>
        /// 承運人編號
        /// </summary>
        [Description("承運人")]
        [Browsable(false)]
        public string ShipperId { get; set; }
        /// <summary>
        /// 供應商編號
        /// </summary>
        [Description("供應商編號")]
        [Browsable(false)]
        public string SupplierId { get; set; }
        /// <summary>
        /// 預定入庫時間
        /// </summary>
        [Description("預定時間")]
        public System.DateTime? ScheduledInboundTime { get; set; }
        /// <summary>
        /// 備註
        /// </summary>
        [Description("備註")]
        [Browsable(false)]
        public string Remark { get; set; }
        /// <summary>
        /// 有效標誌
        /// </summary>
        [Description("有效標誌")]
        public bool Enable { get; set; }
        /// <summary>
        /// 承運方式
        /// </summary>
        [Description("承運方式")]
        public string TransferType { get; set; }
        /// <summary>
        /// 是否入保稅
        /// </summary>
        [Description("是否入保稅庫")]
        public bool InBondedArea { get; set; }
        /// <summary>
        /// 銷退箱數
        /// </summary>
        [Description("銷退箱數")]
        public decimal ReturnBoxNum { get; set; }
        /// <summary>
        /// 建立時間
        /// </summary>
        [Description("建立時間")]
        public System.DateTime CreateTime { get; set; }
        /// <summary>
        /// 建立人ID
        /// </summary>
        [Description("建立人ID")]
        [Browsable(false)]
        public string CreateUserId { get; set; }
        /// <summary>
        /// 建立人
        /// </summary>
        [Description("建立人")]
        public string CreateUserName { get; set; }
        /// <summary>
        /// 最後更新時間
        /// </summary>
        [Description("最後更新")]
        public System.DateTime? UpdateTime { get; set; }
        /// <summary>
        /// 最後更新人ID
        /// </summary>
        [Description("最後更新人ID")]
        [Browsable(false)]
        public string UpdateUserId { get; set; }
        /// <summary>
        /// 最後更新人
        /// </summary>
        [Description("最後更新人")]
        public string UpdateUserName { get; set; }
        
        /// <summary>
        /// 所屬部門
        /// </summary>
        [Description("所屬部門")]
        public string OrgId { get; set; }
    }
}