//------------------------------------------------------------------------------
// <autogenerated>
//     This code was generated by a CodeSmith Template.
//
//     DO NOT MODIFY contents of this file. Changes to this
//     file will be lost if the code is regenerated.
//     Author:Yubao Li
// </autogenerated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.ComponentModel.DataAnnotations.Schema;
using System.Text;
using OpenAuth.Repository.Core;

namespace OpenAuth.App.Request
{
    /// <summary>
	/// 程式碼產生器的表資訊
	/// </summary>
    public partial class AddOrUpdateBuilderTableReq 
    {
        /// <summary>
        /// Id為空則為新增
        /// </summary>
        public string Id { get; set; }
        
        /// <summary>
        /// 表英文全稱
        /// </summary>
        public string TableName { get; set; }
        /// <summary>
        /// 表描述、中文名稱
        /// </summary>
        public string Comment { get; set; }
        /// <summary>
        /// 子表英文全稱
        /// </summary>
        public string DetailTableName { get; set; }
        /// <summary>
        /// 子表描述、中文名稱
        /// </summary>
        public string DetailComment { get; set; }
        /// <summary>
        /// 實體類名稱
        /// </summary>
        public string ClassName { get; set; }
        /// <summary>
        /// 名稱空間
        /// </summary>
        public string Namespace { get; set; }
        /// <summary>
        /// 模組標識
        /// </summary>
        public string ModuleCode { get; set; }
        /// <summary>
        /// 模組名稱
        /// </summary>
        public string ModuleName { get; set; }
        /// <summary>
        /// 程式碼相對資料夾路徑
        /// </summary>
        public string Folder { get; set; }
        /// <summary>
        /// 其它產生選項
        /// </summary>
        public string Options { get; set; }
        /// <summary>
        /// 分類ID
        /// </summary>
        public string TypeId { get; set; }
        /// <summary>
        /// 分類名稱
        /// </summary>
        public string TypeName { get; set; }
    }
}