//------------------------------------------------------------------------------
// <autogenerated>
//     This code was generated by a CodeSmith Template.
//
//     DO NOT MODIFY contents of this file. Changes to this
//     file will be lost if the code is regenerated.
//     Author:Yubao Li
// </autogenerated>
//------------------------------------------------------------------------------

using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;

namespace OpenAuth.App.Request
{
    /// <summary>
	/// 入庫通知單（入庫訂單）
	/// </summary>
    [Table("WmsInboundOrderTbl")]
    public partial class AddOrUpdateWmsInboundOrderTblReq 
    {

        /// <summary>
        /// 入庫通知單號
        /// </summary>
        public string Id { get; set; }
        /// <summary>
        /// 相關單據號
        /// </summary>
        public string ExternalNo { get; set; }
        /// <summary>
        /// 相關單據型別
        /// </summary>
        public string ExternalType { get; set; }
        /// <summary>
        /// 入庫通知單狀態(SYS_INSTCINFORMSTATUS)
        /// </summary>
        public int Status { get; set; }
        /// <summary>
        /// 入庫型別(SYS_INSTCTYPE)
        /// </summary>
        public string OrderType { get; set; }
        /// <summary>
        /// 商品類別
        /// </summary>
        public string GoodsType { get; set; }
        /// <summary>
        /// 採購單號
        /// </summary>
        public string PurchaseNo { get; set; }
        /// <summary>
        /// 倉庫編號
        /// </summary>
        public string StockId { get; set; }
        /// <summary>
        /// 貨主編號(固定值CQM)
        /// </summary>
        public string OwnerId { get; set; }
        /// <summary>
        /// 承運人編號
        /// </summary>
        public string ShipperId { get; set; }
        /// <summary>
        /// 供應商編號
        /// </summary>
        public string SupplierId { get; set; }
        /// <summary>
        /// 預定入庫時間
        /// </summary>
        public System.DateTime? ScheduledInboundTime { get; set; }
        /// <summary>
        /// 備註
        /// </summary>
        public string Remark { get; set; }
        /// <summary>
        /// 有效標誌
        /// </summary>
        public bool Enable { get; set; }
        /// <summary>
        /// 承運方式
        /// </summary>
        public string TransferType { get; set; }
        /// <summary>
        /// 是否入保稅庫(0:否,1:是)
        /// </summary>
        public bool InBondedArea { get; set; }
        /// <summary>
        /// 銷退箱數
        /// </summary>
        public decimal ReturnBoxNum { get; set; }
        
        /// <summary>
        /// 所屬部門
        /// </summary>
        public string OrgId { get; set; }
        
        public List<AddOrUpdateWmsInboundOrderDtblReq> WmsInboundOrderDtblReqs { get; set; }
    }
}