//------------------------------------------------------------------------------
// <autogenerated>
//     This code was generated by a CodeSmith Template.
//
//     DO NOT MODIFY contents of this file. Changes to this
//     file will be lost if the code is regenerated.
//     Author:Yubao Li
// </autogenerated>
//------------------------------------------------------------------------------

using System.ComponentModel.DataAnnotations.Schema;

namespace OpenAuth.App.Request
{
    /// <summary>
	/// 入庫通知單明細
	/// </summary>
    [Table("WmsInboundOrderDtbl")]
    public partial class AddOrUpdateWmsInboundOrderDtblReq 
    {

        /// <summary>
        /// 入庫通知單明細號
        /// </summary>
        public string Id { get; set; }
        /// <summary>
        /// 入庫通知單號
        /// </summary>
        public string OrderId { get; set; }
        /// <summary>
        /// 含稅單價
        /// </summary>
        public decimal? Price { get; set; }
        /// <summary>
        /// 無稅單價
        /// </summary>
        public decimal? PriceNoTax { get; set; }
        /// <summary>
        /// 是否收貨中(0:非收貨中,1:收貨中)
        /// </summary>
        public bool InStockStatus { get; set; }
        /// <summary>
        /// 到貨狀況(SYS_GOODSARRIVESTATUS)
        /// </summary>
        public int AsnStatus { get; set; }
        /// <summary>
        /// 商品編號
        /// </summary>
        public string GoodsId { get; set; }
        /// <summary>
        /// 商品批號
        /// </summary>
        public string GoodsBatch { get; set; }
        /// <summary>
        /// 品質(SYS_QUALITYFLAG)
        /// </summary>
        public string QualityFlg { get; set; }
        /// <summary>
        /// 通知數量
        /// </summary>
        public decimal OrderNum { get; set; }
        /// <summary>
        /// 到貨數量
        /// </summary>
        public decimal InNum { get; set; }
        /// <summary>
        /// 剩餘數量
        /// </summary>
        public decimal LeaveNum { get; set; }
        /// <summary>
        /// 占用數量
        /// </summary>
        public decimal HoldNum { get; set; }
        /// <summary>
        /// 生產日期
        /// </summary>
        public string ProdDate { get; set; }
        /// <summary>
        /// 失效日期
        /// </summary>
        public string ExpireDate { get; set; }
        /// <summary>
        /// 稅率
        /// </summary>
        public decimal? TaxRate { get; set; }
        /// <summary>
        /// 貨主編號
        /// </summary>
        public string OwnerId { get; set; }
        /// <summary>
        /// 備註
        /// </summary>
        public string Remark { get; set; }
    }
}