//------------------------------------------------------------------------------
// <autogenerated>
//     This code was generated by a CodeSmith Template.
//
//     DO NOT MODIFY contents of this file. Changes to this
//     file will be lost if the code is regenerated.
//     Author:Yubao Li
// </autogenerated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.ComponentModel.DataAnnotations.Schema;
using System.Text;
using OpenAuth.Repository.Core;

namespace OpenAuth.App.Request
{
    /// <summary>
	/// 程式碼產生器的欄位資訊
	/// </summary>
    [Table("BuilderTableColumn")]
    public partial class AddOrUpdateBuilderTableColumnReq 
    {

        /// <summary>
        /// 編號
        /// </summary>
        public string Id { get; set; }
        /// <summary>
        /// 歸屬表編號
        /// </summary>
        public string TableId { get; set; }
        /// <summary>
        /// 表名稱
        /// </summary>
        public string TableName { get; set; }
        /// <summary>
        /// 列名稱
        /// </summary>
        public string ColumnName { get; set; }
        /// <summary>
        /// 列描述
        /// </summary>
        public string Comment { get; set; }
        /// <summary>
        /// 列型別
        /// </summary>
        public string ColumnType { get; set; }
        /// <summary>
        /// 實體型別
        /// </summary>
        public string EntityType { get; set; }
        /// <summary>
        /// 實體名稱
        /// </summary>
        public string EntityName { get; set; }
        /// <summary>
        /// 是否主鍵
        /// </summary>
        public bool IsKey { get; set; }
        /// <summary>
        /// 是否自增
        /// </summary>
        public bool IsIncrement { get; set; }
        /// <summary>
        /// 是否必填
        /// </summary>
        public bool IsRequired { get; set; }
        /// <summary>
        /// 是否為插入欄位
        /// </summary>
        public bool IsInsert { get; set; }
        /// <summary>
        /// 是否編輯欄位
        /// </summary>
        public bool IsEdit { get; set; }
        /// <summary>
        /// 是否列表欄位
        /// </summary>
        public bool IsList { get; set; }
        /// <summary>
        /// 是否查詢欄位
        /// </summary>
        public bool IsQuery { get; set; }
        /// <summary>
        /// 查詢方式（等於、不等於、大於、小於、範圍）
        /// </summary>
        public string QueryType { get; set; }
        /// <summary>
        /// 顯示型別（文字框、文字域、下拉框、覈取方塊、單選框、日期控制元件）
        /// </summary>
        public string HtmlType { get; set; }
        /// <summary>
        /// 編輯型別（文字框、文字域、下拉框、覈取方塊、單選框、日期控制元件）
        /// </summary>
        public string EditType { get; set; }
        /// <summary>
        /// 排序
        /// </summary>
        public int Sort { get; set; }
        /// <summary>
        /// 建立時間
        /// </summary>
        public System.DateTime CreateTime { get; set; }
        /// <summary>
        /// 建立人ID
        /// </summary>
        public string CreateUserId { get; set; }
        /// <summary>
        /// 修改時間
        /// </summary>
        public System.DateTime? UpdateTime { get; set; }
        /// <summary>
        /// 修改人ID
        /// </summary>
        public string UpdateUserId { get; set; }
        /// <summary>
        /// 修改時的行位置
        /// </summary>
        public int? EditRow { get; set; }
        /// <summary>
        /// 修改時的列位置
        /// </summary>
        public int? EditCol { get; set; }
        /// <summary>
        /// 修改人姓名
        /// </summary>
        public string UpdateUserName { get; set; }
        /// <summary>
        /// 建立人姓名
        /// </summary>
        public string CreateUserName { get; set; }
        /// <summary>
        /// 最大長度
        /// </summary>
        public int? MaxLength { get; set; }
        
        /// <summary>
        /// 資料來源（用於下拉框、覈取方塊等取值）
        /// </summary>
        public string DataSource { get; set; }
        
         //todo:新增自己的請求欄位
    }
}