//------------------------------------------------------------------------------
// <autogenerated>
//     This code was generated by a CodeSmith Template.
//
//     DO NOT MODIFY contents of this file. Changes to this
//     file will be lost if the code is regenerated.
//     Author:Yubao Li
// </autogenerated>
//------------------------------------------------------------------------------

namespace OpenAuth.App.Response
{
    /// <summary>
	/// 表單模板表
	/// </summary>
    public class FormResp 
    {
        /// <summary>
	    /// 表單名稱
	    /// </summary>
        public string Id { get; set; }

        /// <summary>
	    /// 表單名稱
	    /// </summary>
        public string Name { get; set; }
        /// <summary>
	    /// 欄位個數
	    /// </summary>
        public int Fields { get; set; }
        /// <summary>
        /// 表單型別，0：預設動態表單；1：Web自定義表單
        /// </summary>
        public int FrmType { get; set; }
        /// <summary>
        /// 系統頁面標識，當表單型別為用Web自定義的表單時，需要標識載入哪個頁面
        /// </summary>
        public string WebId { get; set; }
        /// <summary>
	    /// 表單中的欄位數據
	    /// </summary>
        public string ContentData { get; set; }
        /// <summary>
	    /// 表單替換的模板 經過處理
	    /// </summary>
        public string ContentParse { get; set; }
        /// <summary>
	    /// 表單原html模板未經處理的
	    /// </summary>
        public string Content { get; set; }

        /// <summary>
        /// 排序碼
        /// </summary>
        public int SortCode { get; set; }

        public string Description { get; set; }


        /// <summary>
	    /// 資料庫名稱
	    /// </summary>
        public string DbName { get; set; }
        /// <summary>
        /// 使用者顯示
        /// </summary>
        public string Html
        {
            get { return FormUtil.GetHtml(this); }
        }

    }
}